base/urls.py
from django.urls import path
from . import views

app_name='base'

urlpatterns = [
    path('login/', views.loginPage, name="login"),
    path('logout/', views.logoutUser, name="logout"),
    path('register/', views.registerPage, name="register"),

    path('', views.home, name="home"),
    path('room/<int:pk>/', views.room, name="room"),
    path('create-room/', views.createRoom, name="createRoom"),
    path('update-room/<int:pk>/', views.updateRoom, name="updateRoom"),
    path('delete-room/<int:pk>/', views.deleteRoom, name="deleteRoom"),
]

studybud/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('base.urls'))
]

base/models.py
from django.db import models
from django.contrib.auth.models import User

class Topic(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name

class Room(models.Model):
    host = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    topic = models.ForeignKey(Topic, on_delete=models.SET_NULL, null=True)
    name = models.CharField(max_length=200)
    description = models.TextField(null=True, blank=True)
    #participants = 
    updated = models.DateField(auto_now=True)
    created = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.name

class Message(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    room = models.ForeignKey(Room, on_delete=models.CASCADE)
    body = models.TextField()
    updated = models.DateField(auto_now=True)
    created = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.body[0:50]

base/forms.py
from django.forms import ModelForm
from .models import Room

class RoomForm(ModelForm):
    class Meta:
        model = Room
        fields = '__all__'

base/views.py
from multiprocessing import context
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import UserCreationForm
from .models import Room, Topic
from .forms import RoomForm

#rooms = [
#    {'id':1,'name':'go'},
#    {'id':2,'name':'javascript'},
#    {'id':3,'name':'python'},
#    ]

def loginPage(request):
    page='login'
    if request.user.is_authenticated:
        return redirect('base:home')

    if request.method == 'POST':
        username = request.POST.get('username').lower()
        password = request.POST.get('password')
        try:
            user = User.objects.get(username=username)
        except:
            messages.error(request,'User does not exist')

        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request,user)
            return redirect('base:home')
        else:
            messages.error(request,'Username or password does not exist')
    context = {'page':page}
    return render(request,'base/login_register.html',context)

def logoutUser(request):
    logout(request)
    return redirect('base:login')

def registerPage(request):
    form = UserCreationForm()
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.usernam = user.username.lower()
            user.save()
            return redirect('base:login')
        else:
            messages.error(request, 'An error ocurred during registration try again in a few moment')
    context = {'form':form}
    return render(request, 'base/login_register.html',context)

def home(request):
    q = request.GET.get('q') if request.GET.get('q') != None else ''
    rooms=Room.objects.filter(
     Q(topic__name__icontains=q) |
     Q(name__icontains=q) |
     Q(description__icontains=q)
     )
    #rooms=Room.objects.all()
    topics = Topic.objects.all()
    room_count = rooms.count()
    context={'rooms':rooms,'topics':topics, 'room_count':room_count}
    return render(request, 'base/home.html', context)

def room(request, pk):
    room = Room.objects.get(id=pk)
    context = {'room':room}
    return render(request, 'base/room.html', context)

@login_required(login_url='base:login')
def createRoom(request):
    form = RoomForm()

    if request.method == 'POST':
        form = RoomForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('base:home')
    context = {'form': form}
    return render(request, 'base/room_form.html', context)

@login_required(login_url='base:login')
def updateRoom(request,pk):
    room = Room.objects.get(id=pk)
    form = RoomForm(instance=room)

    if request.user != room.host:
        return HttpResponse('you are not allowed here!!')

    if request.method == 'POST':
        form = RoomForm(request.POST, instance=room)
        if form.is_valid():
            form.save()
            return redirect('base:home')
    context = {'form':form}
    return render(request, 'base/room_form.html', context)

@login_required(login_url='base:login')
def deleteRoom(request,pk):
    room = Room.objects.get(id=pk)
    if request.user != room.host:
        return HttpResponse('you are not allowed here!!')
        
    if request.method == 'POST':
        room.delete()
        return redirect('base:home')
    return render(request, 'base/delete.html', {'obj':room})

base/templates/base/delete.html
{% extends 'layout.html' %}
{% block content %}

<form action="" method="post">
    {% csrf_token %}
    <p>Are you sure you want to delete "{{obj}}"?</p>
    <a href="{{request.META.HTTP_REFERER}}">Go back</a>
    <input type="submit" value="Confirm" />
</form>

{% endblock %}

base/templates/base/home.html
{% extends 'layout.html' %}
{% block content %}

<style>
    .home-container{
        display: grid;
        grid-template-columns: 1fr 3fr;
    }
</style>

<div class="home-container">

    <div>
        <h3>Browse Topics</h3>
        <hr>
        <div>
            <a href="{% url 'base:home' %}">All</a>
        </div>
        {% for topic in topics %}
        <div>
            <a href="{% url 'base:home' %}?q={{ topic.name }}">{{ topic.name }}</a>
        </div>
        {% endfor %}

    </div>

    <div>
        <h5>{{room_count}} rooms available</h5>
        <a href="{% url 'base:createRoom' %}">Create Room</a>
        <div>
            {% for room in rooms %}
            <div>
                {% if request.user == room.host %}
                <a href="{% url 'base:updateRoom' room.id %}">Edit</a>
                <a href="{% url 'base:deleteRoom' room.id %}">Delete</a>
                {% endif %}
                <span>@{{room.host.username}}</span>
                <h5>{{room.id}} -- <a href="{% url 'base:room' room.id %}">{{room.name}}</a></h5>
                <small>{{room.topic.name}}</small>
                <hr>
            </div>
            {% endfor %}
        </div>
    </div>
    
</div>

{% endblock %}

base/templates/base/login_register.html
{% extends 'layout.html' %}
{% block content %}

{% if page == 'login' %}
<div>
    <form action="" method="post">
        {% csrf_token %}
        <label for="">Username:</label>
        <input type="text" name="username" placeholder="Enter Username" />
        <label for="">Password:</label>
        <input type="password" name="password" placeholder="Enter Password" />
        <input type="submit" value="Login" />
    </form>
    <p>havent signed up yet?</p>
    <a href="{% url 'base:register' %}">Sign up</a>
</div>

{% else %}
<div>
    <form action="" method="post">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="Register" />
    </form>
    <p>alredy signed up yet?</p>
    <a href="{% url 'base:login' %}">Login</a>
</div>
{% endif %}
{% endblock %}

base/templates/base/room.html
{% extends 'layout.html' %}
{% block content %}
<h1>{{ room.name }}</h1>
{% endblock %}

base/templates/base/room_form.html
{% extends 'layout.html' %}
{% block content %}

<div>
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Submit" />
    </form>
</div>

{% endblock %}

templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>StudyBud</title>
</head>
<body>
    {% include 'navbar.html' %}

    {% if messages %}
    <ul class="messages">
        {% for message in messages %}
        <li>{{ message }}</li>
        {% endfor %}
    </ul>
    {% endif %}

    {% block content %}
    {% endblock %}
</body>
</html>

templates/navbar.html
<a href="/">
    <h1>logo</h1>
</a>

<a href="/room">
    <h1>room</h1>
</a>

<form action="{% url 'base:home' %}" method="get">
    <input type="text" name="q" placeholder="Search Rooms..." />
</form>

{% if request.user.is_authenticated %}
<p>Hello {{request.user}}</p>
<a href="{% url 'base:logout' %}">Logout</a>
{% else %}
<a href="{% url 'base:login' %}">Login</a>
{% endif %}
<hr>